---
data_center_routers:
  hosts:
    cali:
      ansible_host: 192.168.0.158

network:
  children:
    data_center_routers
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: cisco
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: cisco




